# Generated by Django 3.1.7 on 2021-06-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chuckapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='Joke',
        ),
    ]
